version: "3.7"

x-logging: &default-logging
  options:
    max-size: "100m"
    max-file: "1"
  driver: json-file

services:
  hoster:
    image: dvdarias/docker-hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
    restart: unless-stopped
    logging: *default-logging

  redis:
    image: redis
    expose:
      - 6379
    restart: unless-stopped
    logging: *default-logging

  traefik:
    image: traefik:2.6.1
    command: "--configFile=/traefik/static.yaml"
    restart: unless-stopped
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    networks:
      default:
        aliases:
        - stocra.com
        - "*.stocra.com"
    volumes:
      - ./traefik/:/traefik:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    logging: *default-logging

networks:
  default:
    name: stocra
