x-logging: &default-logging
  options:
    max-size: "100m"
    max-file: "1"
  driver: json-file

services:
  node:
    volumes:
      - ./datadir/node/:/node/datadir/
    expose:
      - 8000
    stop_grace_period: 10m
    restart: unless-stopped
    build: .
    logging: *default-logging

  sidecar:
    image: sidecar
    restart: unless-stopped
    expose:
      - 8000
    env_file: .env
    logging: *default-logging
    deploy:
      replicas: 4
    depends_on:
      - node

  precacher:
    image: precacher
    restart: unless-stopped
    env_file: .env
    logging: *default-logging
    depends_on:
      - node
      - sidecar

networks:
  default:
    name: stocra
    external: true
