entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
    http:
      tls: true

providers:
  file:
    directory: "/traefik/"
    watch: true

log:
  level: WARN
