- hosts: all
  become: true
  tasks:
  - name: Add apt keys for docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add repository for docker
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present
  - name: Install packages
    package:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - git
        - python3
        - python3-pip
        - certbot
        - vim
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
      update_cache: true
  - name: Make python python3
    file:
      src: /usr/bin/python3
      dest: /usr/bin/python
      state: link
  - name: Install docker python package
    ansible.builtin.pip:
      name:
      - docker
      - docker-compose
  - name: Remove old docker-compose binary
    ansible.builtin.file:
      path: /usr/local/bin/docker-compose
      state: absent
  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/v2.4.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
  - name: Download netdata agent
    get_url:
      url: https://my-netdata.io/kickstart.sh
      dest: /tmp/netdata-kickstart.sh
  - name: Install netdata agent
    shell: |
      sh /tmp/netdata-kickstart.sh \ 
        --claim-token \ 
        <netdata token> \ 
        --claim-url \
        https://app.netdata.cloud \ 
      || true
  - name: Set hostname
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"
  - name: Create project dir
    file:
      path: /projects/stocra/
      state: directory
  - include_tasks: ../tasks/copy_certificates.yaml
  - name: Reboot
    ansible.builtin.reboot:
