x-logging: &default-logging
  options:
    max-size: "100m"
    max-file: "1"
  driver: json-file

services:
  node:
    image: cardano-node
    build:
      context: .
      target: node
    environment:
      NETWORK: mainnet
    stop_signal: SIGINT
    stop_grace_period: 10m

  postgres:
    image: postgres:11.5-alpine
    expose:
      - 5432
    volumes:
      - ./datadir/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    logging: *default-logging

  dbsync:
    image: cardano-dbsync
    build:
      context: .
      target: dbsync
    environment:
      - POSTGRES_HOST=cardano-postgres-1
      - POSTGRES_PORT=5432
    depends_on:
      - node
      - postgres
    volumes:
      - ./datadir/:/node/datadir/
    restart: on-failure
    logging: *default-logging
    stop_signal: SIGINT
    stop_grace_period: 10m
