version: "3.4"
x-environment:
  &default-environment
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
  SECRET_KEY: <secret key>
  PORT: 8000
  EMAIL_URL: <SMTP URL> # https://glitchtip.com/documentation/install#configuration
  GLITCHTIP_DOMAIN: <glitchtip domain>
  DEFAULT_FROM_EMAIL: <email>
  CELERY_WORKER_CONCURRENCY: 2
x-depends_on:
  &default-depends_on
  - postgres
  - redis

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: unless-stopped

  web:
    image: glitchtip/glitchtip
    depends_on: *default-depends_on
    ports:
      - "8000:8000"
    environment: *default-environment
    restart: unless-stopped

  worker:
    image: glitchtip/glitchtip
    command: ./bin/run-celery-with-beat.sh
    depends_on: *default-depends_on
    environment: *default-environment
    restart: unless-stopped

  migrate:
    image: glitchtip/glitchtip
    depends_on: *default-depends_on
    command: "./manage.py migrate"
    environment: *default-environment
